[package]
name = "jcalc"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full", "rt-multi-thread"] }
ore_jdwp = { path = "../ore-jdwp" }
clap = { version = "4.5.45", features = ["derive"] }
futures-util = "0.3.31"
atty = "0.2.14"
